## Introduction

In [50]:
import pandas as pd
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["X","Y","Z"])

In [51]:
df.head()

   X  Y  Z
0  1  2  3
1  4  5  6
2  7  8  9

In [52]:
df.describe()

         X    Y    Z
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

## Steam Games loc&iloc

In [53]:
import pandas as pd
sg = pd.read_csv('./found_datasets/steam_games_dataset.csv') #Steam Games dataset

In [54]:
sg.loc[1, "price"] = 6767

In [55]:
sg.loc[1:99,["name","positive","negative","price"]]

                               name  positive  negative  price
1                      Apex Legends    668053    326926   6767
2               PUBG: BATTLEGROUNDS   1520457   1037487      0
3                          Palworld    358266     22443   2999
4                   Team Fortress 2   1044264    117208      0
5   Call of Duty: Modern Warfare II    419594    294520   3849
..                              ...       ...       ...    ...
95                             DayZ    330349     99903   4999
96                     Satisfactory    225479      6585   2799
97                         NBA 2K20     30260     30413      0
98                   Risk of Rain 2    293127     20450   2499
99                EA SPORTS FIFA 23     86192     65227      0

[99 rows x 4 columns]

In [56]:
sg.iloc[0:11, [1,5,6]]

                                name  positive  negative
0   Counter-Strike: Global Offensive   7642084   1173003
1                       Apex Legends    668053    326926
2                PUBG: BATTLEGROUNDS   1520457   1037487
3                           Palworld    358266     22443
4                    Team Fortress 2   1044264    117208
5    Call of Duty: Modern Warfare II    419594    294520
6                New World: Aeternum    196798     90080
7                 Black Myth: Wukong   1111720     38378
8          Grand Theft Auto V Legacy   1739980    250576
9                      Left 4 Dead 2    940221     23762
10                          Unturned    506516     48852

In [ ]:
sg.loc[sg['price'] > 1000, ['Name', 'Price']]

KeyError: "None of [Index(['Name', 'Price'], dtype='str')] are in the [columns]"